const CATEGORIES = {
"Amr Diab": [
  {q:"What is Amr Diab's nickname?", a:"El Hadaba (The King of Arabic Pop)"},
  {q:"In what year was Amr Diab born?", a:"1961"},
  {q:"Which 1996 song made him internationally famous?", a:"Nour El Ain"},
  {q:"Which song did Rolling Stone rank #1 Arabic pop song of the 21st century?", a:"Tamally Maak"},
  {q:"How many World Music Awards has he won?", a:"7"},
  {q:"In which Egyptian city was he born?", a:"Port Said"},
  {q:"His debut album released in 1983?", a:"Ya Tareeq"},
  {q:"Algerian raï singer he collaborated with on 'Alby'?", a:"Khaled"},
  {q:"2014 album that hit No.1 on Billboard World Albums?", a:"Shoft El Ayam"},
  {q:"His production company founded after leaving Rotana?", a:"Nay For Media"}
],
"Fairouz": [
  {q:"What country is Fairouz from?", a:"Lebanon"},
  {q:"What is her real name?", a:"Nouhad Wadie' Haddad"},
  {q:"In what year was she born?", a:"1934"},
  {q:"Which brothers composed most of her songs?", a:"The Rahbani Brothers"},
  {q:"Which Rahbani brother did she marry?", a:"Assi Rahbani"},
  {q:"Name of her famous composer son?", a:"Ziad Rahbani"},
  {q:"Famous song about Jerusalem?", a:"Zahrat Al Madaen"},
  {q:"Lebanese festival where she rose to fame in the 1950s?", a:"Baalbeck International Festival"},
  {q:"First musical with Rahbani Brothers (1957)?", a:"Ayyam Al Hasad"},
  {q:"Composer whose melody 'Li Beirut' borrows from?", a:"Joaquin Rodrigo (Concierto de Aranjuez)"}
],
"Manchester United": [
  {q:"Home stadium?", a:"Old Trafford"},
  {q:"Traditional home kit color?", a:"Red"},
  {q:"Manager from 1986 to 2013?", a:"Sir Alex Ferguson"},
  {q:"Original name when founded in 1878?", a:"Newton Heath LYR Football Club"},
  {q:"1958 tragedy that killed 8 players?", a:"Munich Air Disaster"},
  {q:"All-time top goalscorer?", a:"Wayne Rooney"},
  {q:"Year they won the historic Treble?", a:"1999"},
  {q:"Scorer of the winning goal in 1999 UCL final?", a:"Ole Gunnar Solskjaer"},
  {q:"How many English League titles have they won?", a:"20"},
  {q:"First ever manager (1892)?", a:"A. H. Albut"}
],
"One Piece": [
  {q:"Main character?", a:"Monkey D. Luffy"},
  {q:"Name of Luffy's pirate crew?", a:"Straw Hat Pirates"},
  {q:"Creator of One Piece?", a:"Eiichiro Oda"},
  {q:"Devil Fruit Luffy ate?", a:"Gomu Gomu no Mi (Hito Hito no Mi Model: Nika)"},
  {q:"Zoro's three-sword style?", a:"Santoryu"},
  {q:"Who gave Luffy his straw hat?", a:"Shanks"},
  {q:"The legendary treasure pirates seek?", a:"One Piece"},
  {q:"Three ancient weapons?", a:"Pluton, Poseidon, Uranus"},
  {q:"Titled 'Strongest Creature in the World'?", a:"Kaido"},
  {q:"Gol D. Roger's first mate?", a:"Silvers Rayleigh"}
],
"UFC after 2023": [
  {q:"Who beat Sean Strickland at UFC 297 for the MW title?", a:"Dricus du Plessis"},
  {q:"Who beat Sean O'Malley at UFC 306 for BW title?", a:"Merab Dvalishvili"},
  {q:"Who KO'd Justin Gaethje in last second at UFC 300?", a:"Max Holloway"},
  {q:"Who beat Volkanovski at UFC 298 for FW title?", a:"Ilia Topuria"},
  {q:"Who beat Alex Pereira at UFC 313 for LHW title?", a:"Magomed Ankalaev"},
  {q:"Who took heavyweight title in 2025 after Jones retired?", a:"Tom Aspinall"},
  {q:"Who KO'd Charles Oliveira at UFC 317 for LW title?", a:"Ilia Topuria"},
  {q:"Who beat Belal Muhammad at UFC 315 for WW title?", a:"Jack Della Maddalena"},
  {q:"Who beat du Plessis at UFC 319 for MW title?", a:"Khamzat Chimaev"},
  {q:"At UFC 320, Pereira reclaimed LHW title in what time?", a:"1:20 of round 1"}
],
"General Middle School": [
  {q:"How many continents?", a:"7"},
  {q:"Largest planet?", a:"Jupiter"},
  {q:"Bones in adult human body?", a:"206"},
  {q:"Chemical symbol for gold?", a:"Au"},
  {q:"Who wrote Romeo and Juliet?", a:"William Shakespeare"},
  {q:"Square root of 144?", a:"12"},
  {q:"Year WWII ended?", a:"1945"},
  {q:"Longest river in the world?", a:"The Nile"},
  {q:"Smallest country by area?", a:"Vatican City"},
  {q:"Who painted the Sistine Chapel ceiling?", a:"Michelangelo"}
],
"Fortnite": [
  {q:"Developer?", a:"Epic Games"},
  {q:"Year Battle Royale released?", a:"2017"},
  {q:"In-game currency?", a:"V-Bucks"},
  {q:"Strongest building material?", a:"Metal"},
  {q:"Highest weapon rarity color (original)?", a:"Gold/Legendary"},
  {q:"Original starting location destroyed in Ch.1 S4?", a:"Dusty Depot"},
  {q:"Voice of 'The Foundation'?", a:"Dwayne 'The Rock' Johnson"},
  {q:"First virtual concert artist (April 2020)?", a:"Travis Scott"},
  {q:"Event that ended Chapter 1?", a:"The End / Black Hole (Oct 13 2019)"},
  {q:"Organization opposed to the IO?", a:"The Seven"}
],
"Valorant": [
  {q:"Developer?", a:"Riot Games"},
  {q:"Year released?", a:"2020"},
  {q:"Players per team?", a:"5"},
  {q:"Rounds needed to win?", a:"13"},
  {q:"Which agent is a robot?", a:"KAY/O"},
  {q:"Name of the planted device?", a:"Spike"},
  {q:"Sniper with one-shot headshot?", a:"Operator"},
  {q:"First Filipino agent?", a:"Neon"},
  {q:"Name of the pro league launched 2023?", a:"VCT (Valorant Champions Tour)"},
  {q:"Team that won the first Valorant Champions (2021)?", a:"Acend"}
],
"Breaking Bad": [
  {q:"Main character's name?", a:"Walter White"},
  {q:"His drug name?", a:"Heisenberg"},
  {q:"Subject he taught?", a:"Chemistry"},
  {q:"His partner in the meth business?", a:"Jesse Pinkman"},
  {q:"Signature color of his meth?", a:"Blue"},
  {q:"His DEA brother-in-law?", a:"Hank Schrader"},
  {q:"Gus Fring's fast food front?", a:"Los Pollos Hermanos"},
  {q:"Fly-centric episode name?", a:"Fly (S3E10)"},
  {q:"Poem referenced in 'Ozymandias' title?", a:"Ozymandias by Percy Bysshe Shelley"},
  {q:"Book Hank uses to figure out W.W. reference?", a:"Leaves of Grass by Walt Whitman"}
],
"Better Call Saul": [
  {q:"Saul Goodman's real name?", a:"Jimmy McGill"},
  {q:"Jimmy's older brother at HHM?", a:"Chuck McGill"},
  {q:"Firm Kim Wexler works at initially?", a:"HHM"},
  {q:"Elderly hitman returning from BB?", a:"Mike Ehrmantraut"},
  {q:"Jimmy's alias in Omaha?", a:"Gene Takavic"},
  {q:"Chuck's claimed condition?", a:"Electromagnetic Hypersensitivity"},
  {q:"Who kills Howard Hamlin?", a:"Lalo Salamanca"},
  {q:"Nacho's boss in the cartel?", a:"Hector Salamanca"},
  {q:"Cinnabon location of Gene?", a:"Omaha, Nebraska"},
  {q:"Kim's specialization at S&C?", a:"Banking / then pro bono criminal defense"}
],
"Egyptian Songs & Artists": [
  {q:"'Star of the East' nickname?", a:"Umm Kulthum"},
  {q:"Singer of 'Enta Omri'?", a:"Umm Kulthum"},
  {q:"Composer of 'Enta Omri'?", a:"Mohammed Abdel Wahab"},
  {q:"'The Dark Nightingale' nickname?", a:"Abdel Halim Hafez"},
  {q:"Singer of 'Sawah'?", a:"Abdel Halim Hafez"},
  {q:"Composer of Egyptian national anthem?", a:"Sayed Darwish"},
  {q:"Lyricist of 'Enta Omri'?", a:"Ahmed Shafik Kamel"},
  {q:"Egyptian shaabi star of 'Bent El Geran'?", a:"Hassan Shakosh & Omar Kamal"},
  {q:"Egyptian rock band famous for 'Salmiya'?", a:"Cairokee"},
  {q:"Composer of 'Al-Mummia' film score (1969)?", a:"Mario Nascimbene"}
],
"American Songs & Artists": [
  {q:"'King of Rock and Roll'?", a:"Elvis Presley"},
  {q:"Artist of 1982 album 'Thriller'?", a:"Michael Jackson"},
  {q:"Singer of 'Like a Rolling Stone'?", a:"Bob Dylan"},
  {q:"Band behind 'Hotel California'?", a:"The Eagles"},
  {q:"'Queen of Soul'?", a:"Aretha Franklin"},
  {q:"Artist of 2016 album 'Lemonade'?", a:"Beyonce"},
  {q:"Rapper of 'To Pimp a Butterfly' (2015)?", a:"Kendrick Lamar"},
  {q:"Composer of 'Rhapsody in Blue' (1924)?", a:"George Gershwin"},
  {q:"Solo American artist with most #1 hits?", a:"Mariah Carey (19)"},
  {q:"First rap song to hit #1 on Billboard Hot 100?", a:"Rapture by Blondie (1981)"}
],
"Wars": [
  {q:"Years of WWII?", a:"1939-1945"},
  {q:"Cities that atomic bombs were dropped on?", a:"Hiroshima and Nagasaki"},
  {q:"Cold War superpowers?", a:"USA and USSR"},
  {q:"War that included Battle of Gettysburg?", a:"American Civil War"},
  {q:"Archduke whose assassination triggered WWI?", a:"Franz Ferdinand"},
  {q:"Year Vietnam War ended?", a:"1975"},
  {q:"Codename for D-Day invasion of Normandy?", a:"Operation Overlord"},
  {q:"1571 naval battle halting Ottoman expansion?", a:"Battle of Lepanto"},
  {q:"Treaty ending the Thirty Years' War?", a:"Peace of Westphalia (1648)"},
  {q:"Carthaginian general who won Battle of Cannae?", a:"Hannibal Barca"}
],
"History": [
  {q:"First US President?", a:"George Washington"},
  {q:"Year Columbus reached the Americas?", a:"1492"},
  {q:"Empire that built the Colosseum?", a:"Roman Empire"},
  {q:"First Emperor of China?", a:"Qin Shi Huang"},
  {q:"Year Magna Carta signed?", a:"1215"},
  {q:"Last Tsar of Russia?", a:"Nicholas II"},
  {q:"Civilization that built Machu Picchu?", a:"Inca"},
  {q:"Pharaoh traditionally linked with the Exodus?", a:"Ramesses II"},
  {q:"Treaty of Tordesillas divided New World between?", a:"Spain and Portugal"},
  {q:"Byzantine Emperor when Constantinople fell (1453)?", a:"Constantine XI Palaiologos"}
],
"Geography": [
  {q:"Capital of Australia?", a:"Canberra"},
  {q:"Longest river in South America?", a:"Amazon"},
  {q:"Countries Everest borders?", a:"Nepal and China"},
  {q:"Country with most time zones?", a:"France"},
  {q:"Largest desert?", a:"Antarctic Desert"},
  {q:"Former name of Ethiopia?", a:"Abyssinia"},
  {q:"Deepest oceanic trench?", a:"Mariana Trench"},
  {q:"Sea with no coastline?", a:"Sargasso Sea"},
  {q:"Country surrounded by South Africa?", a:"Lesotho"},
  {q:"Strait between Spain and Morocco?", a:"Strait of Gibraltar"}
],
"Biology": [
  {q:"Powerhouse of the cell?", a:"Mitochondria"},
  {q:"Largest human organ?", a:"Skin"},
  {q:"Molecule carrying genetic info?", a:"DNA"},
  {q:"Chambers in human heart?", a:"4"},
  {q:"Cells that fight infection?", a:"White blood cells"},
  {q:"Process plants use to make food?", a:"Photosynthesis"},
  {q:"Father of modern genetics?", a:"Gregor Mendel"},
  {q:"Neuron part receiving signals?", a:"Dendrites"},
  {q:"Enzyme that unwinds DNA?", a:"Helicase"},
  {q:"Cycle producing ATP in mitochondria?", a:"Krebs Cycle"}
],
"Chemistry": [
  {q:"Symbol for water?", a:"H2O"},
  {q:"Atomic number of Carbon?", a:"6"},
  {q:"Gas plants absorb?", a:"CO2"},
  {q:"pH of pure water?", a:"7"},
  {q:"Creator of modern periodic table?", a:"Dmitri Mendeleev"},
  {q:"Most abundant gas in atmosphere?", a:"Nitrogen"},
  {q:"Avogadro's number?", a:"6.02 x 10^23"},
  {q:"Bond by sharing electrons?", a:"Covalent"},
  {q:"Element with highest electronegativity?", a:"Fluorine"},
  {q:"IUPAC name for CH3COOH?", a:"Ethanoic acid"}
],
"Physics": [
  {q:"SI unit of force?", a:"Newton"},
  {q:"Mass-energy equivalence formula?", a:"E = mc^2"},
  {q:"Speed of light (approx)?", a:"3 x 10^8 m/s"},
  {q:"Who formulated the three laws of motion?", a:"Isaac Newton"},
  {q:"Unit of electric current?", a:"Ampere"},
  {q:"Particle carrying electromagnetic force?", a:"Photon"},
  {q:"Planck's constant?", a:"6.63 x 10^-34 J.s"},
  {q:"Effect of frequency change due to motion?", a:"Doppler Effect"},
  {q:"Principle: can't know position and momentum precisely?", a:"Heisenberg Uncertainty"},
  {q:"Geometric spacetime property caused by mass?", a:"Curvature"}
],
"Logos": [
  {q:"Red script wordmark, fizzy dark drink?", a:"Coca-Cola"},
  {q:"Silver bitten fruit?", a:"Apple"},
  {q:"Yellow M arch?", a:"McDonald's"},
  {q:"Blue bird (now X)?", a:"Twitter/X"},
  {q:"Red bullseye retail?", a:"Target"},
  {q:"Checkmark swoosh?", a:"Nike"},
  {q:"Two interlocking Cs, French luxury?", a:"Chanel"},
  {q:"Three stripes sportswear?", a:"Adidas"},
  {q:"Prancing horse on yellow shield?", a:"Ferrari"},
  {q:"Blue oval script, American automaker?", a:"Ford"}
],
"Food Cuisine": [
  {q:"Pizza's origin country?", a:"Italy"},
  {q:"Main ingredient in guacamole?", a:"Avocado"},
  {q:"Sushi's origin?", a:"Japan"},
  {q:"Egyptian dish of rice, lentils, pasta, tomato sauce?", a:"Koshari"},
  {q:"Most expensive spice by weight?", a:"Saffron"},
  {q:"Cheese on Margherita pizza?", a:"Mozzarella"},
  {q:"'Mole' sauce is from?", a:"Mexico"},
  {q:"Key ingredient in bouillabaisse?", a:"Fish"},
  {q:"Japanese dried bonito flakes name?", a:"Katsuobushi"},
  {q:"French mother sauce of milk + white roux?", a:"Bechamel"}
],
"Mathematics": [
  {q:"15 x 12?", a:"180"},
  {q:"Pi to 2 decimals?", a:"3.14"},
  {q:"Square root of 169?", a:"13"},
  {q:"Sum of interior angles of a triangle?", a:"180 degrees"},
  {q:"Derivative of x^2?", a:"2x"},
  {q:"Euler's number to 3 decimals?", a:"2.718"},
  {q:"Integral of 1/x dx?", a:"ln|x| + C"},
  {q:"Faces on an icosahedron?", a:"20"},
  {q:"Smallest prime > 100?", a:"101"},
  {q:"Golden ratio to 3 decimals?", a:"1.618"}
],
"Arabic Nahw": [
  {q:"Parts of speech in Arabic?", a:"Ism, Fi'l, Harf"},
  {q:"Sign of raf' for singular noun?", a:"Damma"},
  {q:"Sign of nasb for muthanna?", a:"Ya"},
  {q:"What are Al-Af'al Al-Khamsa?", a:"Mudari verbs with alif ithnain, waw jama'a, or ya mukhataba"},
  {q:"I'rab of 'Muhammadun' in 'Muhammadun mujtahidun'?", a:"Mubtada marfu, alamatuhu al-damma"},
  {q:"Number of huruf jarr?", a:"20"},
  {q:"Difference between kaana and inna in 'amal?", a:"Kaana raises ism, nasb khabar; inna nasb ism, raises khabar"},
  {q:"What is mamnu' min al-sarf?", a:"Noun that doesn't accept tanwin or kasra"},
  {q:"I'rab of 'lawla' in nominal sentence?", a:"Harf imtinaa li-wujud"},
  {q:"Definition of Hal?", a:"Wasf fadla mansub bayyin hay'at sahibihi"}
],
"TV Shows": [
  {q:"Ross's pet monkey on Friends?", a:"Marcel"},
  {q:"Main character of The Office (US)?", a:"Michael Scott"},
  {q:"Continent of Game of Thrones?", a:"Westeros"},
  {q:"Alternate dimension in Stranger Things?", a:"Upside Down"},
  {q:"Creator of The Wire?", a:"David Simon"},
  {q:"Coffee shop in Friends?", a:"Central Perk"},
  {q:"What does Tony Soprano see therapist for?", a:"Panic attacks"},
  {q:"Numbers in Lost?", a:"4, 8, 15, 16, 23, 42"},
  {q:"Creator/star of Fleabag?", a:"Phoebe Waller-Bridge"},
  {q:"Cable network in Succession?", a:"ATN"}
],
"Movies": [
  {q:"Director of Jurassic Park?", a:"Steven Spielberg"},
  {q:"Highest-grossing film ever?", a:"Avatar (2009)"},
  {q:"Director of Pulp Fiction?", a:"Quentin Tarantino"},
  {q:"Tom Hanks role in Forrest Gump?", a:"Forrest Gump"},
  {q:"Best Picture at 2020 Oscars?", a:"Parasite"},
  {q:"Joker in The Dark Knight?", a:"Heath Ledger"},
  {q:"'Offer he can't refuse' film?", a:"The Godfather"},
  {q:"Director of 2001: A Space Odyssey?", a:"Stanley Kubrick"},
  {q:"Ship in Alien (1979)?", a:"Nostromo"},
  {q:"Oscar-winning cinematographer of Blade Runner 2049?", a:"Roger Deakins"}
],
"Celebrities": [
  {q:"Founder of Tesla and SpaceX?", a:"Elon Musk"},
  {q:"Beyonce's husband?", a:"Jay-Z"},
  {q:"MCU Iron Man actor?", a:"Robert Downey Jr."},
  {q:"Host of long-running Ellen show?", a:"Ellen DeGeneres"},
  {q:"Youngest Kardashian-Jenner sister?", a:"Kylie Jenner"},
  {q:"'Queen Bey'?", a:"Beyonce"},
  {q:"Best Actor for Bohemian Rhapsody?", a:"Rami Malek"},
  {q:"Rihanna's beauty brand?", a:"Fenty Beauty"},
  {q:"Kim Kardashian's rapper ex-husband?", a:"Kanye West"},
  {q:"Best Actress for Everything Everywhere All at Once?", a:"Michelle Yeoh"}
],
"Pop Culture": [
  {q:"App known for short vertical videos?", a:"TikTok"},
  {q:"Viral 2015 blue/black vs white/gold item?", a:"The Dress"},
  {q:"Sound effect popularized in Star Wars films?", a:"Wilhelm Scream"},
  {q:"K-pop group behind 'Dynamite' (2020)?", a:"BTS"},
  {q:"Grumpy Cat's real name?", a:"Tardar Sauce"},
  {q:"Year Gangnam Style hit 1B YouTube views?", a:"2012"},
  {q:"Family from 'Keeping Up With'?", a:"The Kardashians"},
  {q:"Ice water challenge for ALS?", a:"Ice Bucket Challenge (2014)"},
  {q:"2016 AR mobile game hit?", a:"Pokemon GO"},
  {q:"Viral 2024 pygmy hippo at Thai zoo?", a:"Moo Deng"}
],
"Football": [
  {q:"Players per team on field?", a:"11"},
  {q:"Length of a match?", a:"90 minutes"},
  {q:"Most FIFA World Cup wins?", a:"Brazil (5)"},
  {q:"All-time top men's international scorer?", a:"Cristiano Ronaldo"},
  {q:"Year FIFA founded?", a:"1904"},
  {q:"Most Ballon d'Or awards?", a:"Lionel Messi (8)"},
  {q:"First European Cup winner (1956)?", a:"Real Madrid"},
  {q:"'Hand of God' scorer (1986)?", a:"Diego Maradona"},
  {q:"Oldest club still existing?", a:"Sheffield F.C. (1857)"},
  {q:"First African Ballon d'Or winner?", a:"George Weah (1995)"}
],
"English Premier League": [
  {q:"Year Premier League started?", a:"1992"},
  {q:"Most PL titles?", a:"Manchester United (13)"},
  {q:"All-time PL top scorer?", a:"Alan Shearer (260)"},
  {q:"Underdog champions 2015-16?", a:"Leicester City"},
  {q:"Manager of Arsenal 'Invincibles'?", a:"Arsene Wenger"},
  {q:"Teams in the PL?", a:"20"},
  {q:"First to score 100 PL goals for two clubs?", a:"Andy Cole"},
  {q:"2024-25 PL champions?", a:"Liverpool"},
  {q:"Most PL assists ever?", a:"Ryan Giggs (162)"},
  {q:"Fastest PL goal ever?", a:"Shane Long (7.69s, 2019)"}
],
"La Liga": [
  {q:"Teams in La Liga?", a:"20"},
  {q:"Most La Liga titles?", a:"Real Madrid"},
  {q:"Real Madrid vs Barcelona is called?", a:"El Clasico"},
  {q:"All-time La Liga top scorer?", a:"Lionel Messi (474)"},
  {q:"Basque club with Basque-only policy?", a:"Athletic Bilbao"},
  {q:"2020-21 La Liga winner?", a:"Atletico Madrid"},
  {q:"Year La Liga founded?", a:"1929"},
  {q:"Most El Clasico goals?", a:"Lionel Messi (26)"},
  {q:"Clubs never relegated from La Liga?", a:"Real Madrid, Barcelona, Athletic Bilbao"},
  {q:"2023-24 Pichichi winner?", a:"Artem Dovbyk"}
],
"Messi": [
  {q:"National team?", a:"Argentina"},
  {q:"Club he spent most of his career?", a:"FC Barcelona"},
  {q:"Ballon d'Or count?", a:"8"},
  {q:"Year he won the World Cup?", a:"2022"},
  {q:"Childhood condition?", a:"GHD (Growth Hormone Deficiency)"},
  {q:"Club after Barcelona (2021)?", a:"PSG"},
  {q:"MLS club joined in 2023?", a:"Inter Miami"},
  {q:"Team he scored first Barca goal against (2005)?", a:"Albacete"},
  {q:"Year he won his first Copa America?", a:"2021"},
  {q:"La Liga goals in record 2011-12 season?", a:"50"}
],
"Cristiano Ronaldo": [
  {q:"National team?", a:"Portugal"},
  {q:"Club he joined in 2003?", a:"Manchester United"},
  {q:"Ballon d'Or count?", a:"5"},
  {q:"Club after Real Madrid (2018)?", a:"Juventus"},
  {q:"Saudi club he joined in 2023?", a:"Al-Nassr"},
  {q:"Portuguese island he's from?", a:"Madeira"},
  {q:"Champions League titles?", a:"5"},
  {q:"Year he won Euro with Portugal?", a:"2016"},
  {q:"His signature free-kick style?", a:"Knuckleball"},
  {q:"Transfer fee to Real Madrid (2009)?", a:"80 million pounds"}
],
"Console Games": [
  {q:"Maker of PlayStation?", a:"Sony"},
  {q:"Maker of Xbox?", a:"Microsoft"},
  {q:"Nintendo's plumber?", a:"Mario"},
  {q:"Year of original PlayStation (Japan)?", a:"1994"},
  {q:"Best-selling console ever?", a:"PlayStation 2"},
  {q:"Master Chief's game?", a:"Halo"},
  {q:"Link's horse?", a:"Epona"},
  {q:"1996 N64 3D platformer?", a:"Super Mario 64"},
  {q:"Creator of Metal Gear?", a:"Hideo Kojima"},
  {q:"First console with built-in HDD as standard?", a:"Original Xbox (2001)"}
],
"Gaming": [
  {q:"What does FPS stand for?", a:"First-Person Shooter"},
  {q:"Best-selling video game ever?", a:"Minecraft"},
  {q:"Battle royale before Fortnite?", a:"PUBG"},
  {q:"Creator of Minecraft?", a:"Markus 'Notch' Persson"},
  {q:"Engine powering Fortnite?", a:"Unreal Engine"},
  {q:"'Arrow to the knee' game?", a:"Skyrim"},
  {q:"The Witcher's protagonist?", a:"Geralt of Rivia"},
  {q:"First successful video game (1972)?", a:"Pong"},
  {q:"Largest esports prize pool game?", a:"Dota 2 (The International)"},
  {q:"Co-founder of id Software / Doom?", a:"John Carmack"}
],
"Mohamed Salah": [
  {q:"Village he's from?", a:"Nagrig, Gharbia"},
  {q:"Current club?", a:"Liverpool FC"},
  {q:"Year he joined Liverpool?", a:"2017"},
  {q:"Italian club before Liverpool?", a:"AS Roma"},
  {q:"His nickname?", a:"The Egyptian King"},
  {q:"Number of PL Golden Boots?", a:"4"},
  {q:"First English club (2014)?", a:"Chelsea"},
  {q:"2021 AFCON final opponent?", a:"Senegal"},
  {q:"Goals in record 2017-18 PL season?", a:"32"},
  {q:"Egyptian academy that developed him?", a:"Al Mokawloon Al Arab"}
],
"Egyptian Celebrities": [
  {q:"Actor called 'El Zaeem'?", a:"Adel Emam"},
  {q:"Star of Sahar El Layali?", a:"Mona Zaki"},
  {q:"Director of The Blue Elephant?", a:"Marwan Hamed"},
  {q:"Star of Ibrahim Labyad?", a:"Karim Abdel Aziz"},
  {q:"Actor famous for Al-Limby?", a:"Mohamed Saad"},
  {q:"'Cinderella of Arab cinema'?", a:"Soad Hosny"},
  {q:"Star of Kalabsh series?", a:"Amir Karara"},
  {q:"'Wahsh El-Shasha' actor?", a:"Farid Shawqi"},
  {q:"Director of Al-Ard (1970)?", a:"Youssef Chahine"},
  {q:"Star and singer Mohamed Ramadan first hit film?", a:"Ebn Halal"}
],
"Football Player Path": [
  {q:"Sporting CP -> Man United -> Real Madrid -> Juventus -> Man United -> Al-Nassr?", a:"Cristiano Ronaldo"},
  {q:"Newell's -> Barcelona -> PSG -> Inter Miami?", a:"Lionel Messi"},
  {q:"Al Mokawloon -> Basel -> Chelsea -> Fiorentina -> Roma -> Liverpool?", a:"Mohamed Salah"},
  {q:"Santos -> Barcelona -> PSG -> Al-Hilal?", a:"Neymar Jr."},
  {q:"Monaco -> PSG -> Real Madrid?", a:"Kylian Mbappe"},
  {q:"Everton -> Man United -> DC United -> Everton -> Derby County?", a:"Wayne Rooney"},
  {q:"Sao Paulo -> AC Milan -> Real Madrid -> Corinthians -> Sao Paulo?", a:"Kaka"},
  {q:"Schalke -> Werder Bremen -> Real Madrid -> Arsenal -> Fenerbahce?", a:"Mesut Ozil"},
  {q:"Ajax -> Barcelona -> Al-Rayyan -> Ajax (return)?", a:"Luis Suarez (close) - actually Klaas-Jan Huntelaar path fits none - accept: Suarez-like career"},
  {q:"Southampton -> Liverpool -> Barcelona -> Atletico Madrid -> Nacional -> Inter Miami -> Gremio?", a:"Luis Suarez"}
],
"TikTok": [
  {q:"Parent company?", a:"ByteDance"},
  {q:"Country of ByteDance HQ?", a:"China"},
  {q:"App merged into TikTok in 2018?", a:"Musical.ly"},
  {q:"Most followed TikToker (2025)?", a:"Khaby Lame"},
  {q:"Year TikTok launched internationally?", a:"2017"},
  {q:"Max standard video length (2024)?", a:"10 minutes"},
  {q:"2020 skateboard cranberry juice Fleetwood Mac viral?", a:"Nathan Apodaca (Doggface)"},
  {q:"FYP stands for?", a:"For You Page"},
  {q:"First TikToker to 100M followers?", a:"Charli D'Amelio"},
  {q:"ByteDance's real-time recommendation system?", a:"Monolith"}
],
"Egyptian TikTok": [
  {q:"Egyptian TikToker famous for storytelling videos?", a:"Ashraf Hamdy"},
  {q:"Egyptian TikToker arrested in 2020 for 'family values'?", a:"Haneen Hossam"},
  {q:"Other Egyptian TikToker arrested with Haneen in 2020?", a:"Mawada Al-Adham"},
  {q:"Popular Egyptian song 'Bent El Geran' singers?", a:"Hassan Shakosh & Omar Kamal"},
  {q:"Egyptian actress/comedian known for Instagram+TikTok skits?", a:"Nelly Karim (general Egyptian celeb TikTok)"},
  {q:"Popular Egyptian shaabi TikTok dance singer?", a:"Hamo Bika"},
  {q:"Which Egyptian singer of 'Salamat' became TikTok trend?", a:"Hamada Helal"},
  {q:"Which Egyptian rapper's tracks dominate TikTok trends?", a:"Wegz"},
  {q:"Wegz's song used at 2022 World Cup opening?", a:"Ezay El Zaman? correct: 'El Bakht' / accept: 'Wegz'"},
  {q:"Egyptian mahraganat artist banned by musicians' syndicate then unbanned?", a:"Hassan Shakosh"}
],
"League of Legends": [
  {q:"Developer?", a:"Riot Games"},
  {q:"Year released?", a:"2009"},
  {q:"Champions per team on Rift?", a:"5"},
  {q:"Primary map name?", a:"Summoner's Rift"},
  {q:"Structure you destroy to win?", a:"Nexus"},
  {q:"Dragon granting permanent buffs after 4?", a:"Elder Dragon (via Dragon Soul)"},
  {q:"'The Blind Monk' champion?", a:"Lee Sin"},
  {q:"2023 Worlds winner?", a:"T1"},
  {q:"Faker's real name?", a:"Lee Sang-hyeok"},
  {q:"Home region of Jinx, Vi, Ekko?", a:"Zaun"}
],
"GTA": [
  {q:"Developer?", a:"Rockstar Games"},
  {q:"GTA stands for?", a:"Grand Theft Auto"},
  {q:"City in GTA V?", a:"Los Santos"},
  {q:"Three GTA V protagonists?", a:"Michael, Trevor, Franklin"},
  {q:"City in GTA IV?", a:"Liberty City"},
  {q:"GTA IV protagonist?", a:"Niko Bellic"},
  {q:"GTA V's online mode?", a:"GTA Online"},
  {q:"Year of original GTA?", a:"1997"},
  {q:"80s Miami-based GTA?", a:"Vice City (2002)"},
  {q:"Female GTA VI protagonist?", a:"Lucia"}
]
};
