const CATEGORIES = {
"Amr Diab": [
  {q:"What is Amr Diabs nickname?", a:"El Hadaba (The King of Arabic Pop)"},
  {q:"In what year was Amr Diab born?", a:"1961"},
  {q:"Which 1996 song made him internationally famous?", a:"Nour El Ain"},
  {q:"Which song did Rolling Stone rank #1 Arabic pop song of the 21st century?", a:"Tamally Maak"},
  {q:"How many World Music Awards has he won?", a:"7"},
  {q:"In which Egyptian city was he born?", a:"Port Said"},
  {q:"His debut album released in 1983?", a:"Ya Tareeq"},
  {q:"Algerian rai singer he collaborated with on Alby?", a:"Khaled"},
  {q:"2014 album that hit No.1 on Billboard World Albums?", a:"Shoft El Ayam"},
  {q:"His production company founded after leaving Rotana?", a:"Nay For Media"}
],
"Fairouz": [
  {q:"What country is Fairouz from?", a:"Lebanon"},
  {q:"What is her real name?", a:"Nouhad Wadie Haddad"},
  {q:"In what year was she born?", a:"1934"},
  {q:"Which brothers composed most of her songs?", a:"The Rahbani Brothers"},
  {q:"Which Rahbani brother did she marry?", a:"Assi Rahbani"},
  {q:"Name of her famous composer son?", a:"Ziad Rahbani"},
  {q:"Famous song about Jerusalem?", a:"Zahrat Al Madaen"},
  {q:"Lebanese festival where she rose to fame in the 1950s?", a:"Baalbeck International Festival"},
  {q:"First musical with Rahbani Brothers (1957)?", a:"Ayyam Al Hasad"},
  {q:"Composer whose melody Li Beirut borrows from?", a:"Joaquin Rodrigo (Concierto de Aranjuez)"}
],
"Manchester United": [
  {q:"Home stadium?", a:"Old Trafford"},
  {q:"Traditional home kit color?", a:"Red"},
  {q:"Manager from 1986 to 2013?", a:"Sir Alex Ferguson"},
  {q:"Original name when founded in 1878?", a:"Newton Heath LYR Football Club"},
  {q:"1958 tragedy that killed 8 players?", a:"Munich Air Disaster"},
  {q:"All-time top goalscorer?", a:"Wayne Rooney"},
  {q:"Year they won the historic Treble?", a:"1999"},
  {q:"Scorer of the winning goal in 1999 UCL final?", a:"Ole Gunnar Solskjaer"},
  {q:"How many English League titles have they won?", a:"20"},
  {q:"First ever manager (1892)?", a:"A. H. Albut"}
],
"One Piece": [
  {q:"Main character?", a:"Monkey D. Luffy"},
  {q:"Name of Luffys pirate crew?", a:"Straw Hat Pirates"},
  {q:"Creator of One Piece?", a:"Eiichiro Oda"},
  {q:"Devil Fruit Luffy ate?", a:"Gomu Gomu no Mi (Hito Hito no Mi Model: Nika)"},
  {q:"Zoros three-sword style?", a:"Santoryu"},
  {q:"Who gave Luffy his straw hat?", a:"Shanks"},
  {q:"The legendary treasure pirates seek?", a:"One Piece"},
  {q:"Three ancient weapons?", a:"Pluton, Poseidon, Uranus"},
  {q:"Titled Strongest Creature in the World?", a:"Kaido"},
  {q:"Gol D. Rogers first mate?", a:"Silvers Rayleigh"}
],
"UFC after 2023": [
  {q:"Who beat Sean Strickland at UFC 297 for the MW title?", a:"Dricus du Plessis"},
  {q:"Who beat Sean OMalley at UFC 306 for BW title?", a:"Merab Dvalishvili"},
  {q:"Who KOd Justin Gaethje in last second at UFC 300?", a:"Max Holloway"},
  {q:"Who beat Volkanovski at UFC 298 for FW title?", a:"Ilia Topuria"},
  {q:"Who beat Alex Pereira at UFC 313 for LHW title?", a:"Magomed Ankalaev"},
  {q:"Who took heavyweight title in 2025 after Jones retired?", a:"Tom Aspinall"},
  {q:"Who KOd Charles Oliveira at UFC 317 for LW title?", a:"Ilia Topuria"},
  {q:"Who beat Belal Muhammad at UFC 315 for WW title?", a:"Jack Della Maddalena"},
  {q:"Who beat du Plessis at UFC 319 for MW title?", a:"Khamzat Chimaev"},
  {q:"At UFC 320, Pereira reclaimed LHW title in what time?", a:"1:20 of round 1"}
],
"General Middle School": [
  {q:"How many continents?", a:"7"},
  {q:"Largest planet?", a:"Jupiter"},
  {q:"Bones in adult human body?", a:"206"},
  {q:"Chemical symbol for gold?", a:"Au"},
  {q:"Who wrote Romeo and Juliet?", a:"William Shakespeare"},
  {q:"Square root of 144?", a:"12"},
  {q:"Year WWII ended?", a:"1945"},
  {q:"Longest river in the world?", a:"The Nile"},
  {q:"Smallest country by area?", a:"Vatican City"},
  {q:"Who painted the Sistine Chapel ceiling?", a:"Michelangelo"}
],
"Fortnite": [
  {q:"Developer?", a:"Epic Games"},
  {q:"Year Battle Royale released?", a:"2017"},
  {q:"In-game currency?", a:"V-Bucks"},
  {q:"Strongest building material?", a:"Metal"},
  {q:"Highest weapon rarity color (original)?", a:"Gold/Legendary"},
  {q:"Original starting location destroyed in Ch.1 S4?", a:"Dusty Depot"},
  {q:"Voice of The Foundation?", a:"Dwayne The Rock Johnson"},
  {q:"First virtual concert artist (April 2020)?", a:"Travis Scott"},
  {q:"Event that ended Chapter 1?", a:"The End / Black Hole (Oct 13 2019)"},
  {q:"Organization opposed to the IO?", a:"The Seven"}
],
"Valorant": [
  {q:"Developer?", a:"Riot Games"},
  {q:"Year released?", a:"2020"},
  {q:"Players per team?", a:"5"},
  {q:"Rounds needed to win?", a:"13"},
  {q:"Which agent is a robot?", a:"KAY/O"},
  {q:"Name of the planted device?", a:"Spike"},
  {q:"Sniper with one-shot headshot?", a:"Operator"},
  {q:"First Filipino agent?", a:"Neon"},
  {q:"Name of the pro league launched 2023?", a:"VCT (Valorant Champions Tour)"},
  {q:"Team that won the first Valorant Champions (2021)?", a:"Acend"}
],
"Breaking Bad": [
  {q:"Main characters name?", a:"Walter White"},
  {q:"His drug name?", a:"Heisenberg"},
  {q:"Subject he taught?", a:"Chemistry"},
  {q:"His partner in the meth business?", a:"Jesse Pinkman"},
  {q:"Signature color of his meth?", a:"Blue"},
  {q:"His DEA brother-in-law?", a:"Hank Schrader"},
  {q:"Gus Frings fast food front?", a:"Los Pollos Hermanos"},
  {q:"Fly-centric episode name?", a:"Fly (S3E10)"},
  {q:"Poem referenced in Ozymandias title?", a:"Ozymandias by Percy Bysshe Shelley"},
  {q:"Book Hank uses to figure out W.W. reference?", a:"Leaves of Grass by Walt Whitman"}
],
"Better Call Saul": [
  {q:"Saul Goodmans real name?", a:"Jimmy McGill"},
  {q:"Jimmys older brother at HHM?", a:"Chuck McGill"},
  {q:"Firm Kim Wexler works at initially?", a:"HHM"},
  {q:"Elderly hitman returning from BB?", a:"Mike Ehrmantraut"},
  {q:"Jimmys alias in Omaha?", a:"Gene Takavic"},
  {q:"Chucks claimed condition?", a:"Electromagnetic Hypersensitivity"},
  {q:"Who kills Howard Hamlin?", a:"Lalo Salamanca"},
  {q:"Nachos boss in the cartel?", a:"Hector Salamanca"},
  {q:"Cinnabon location of Gene?", a:"Omaha, Nebraska"},
  {q:"Kims specialization at S&C?", a:"Banking / then pro bono criminal defense"}
],
"Egyptian Songs & Artists": [
  {q:"Star of the East nickname?", a:"Umm Kulthum"},
  {q:"Singer of Enta Omri?", a:"Umm Kulthum"},
  {q:"Composer of Enta Omri?", a:"Mohammed Abdel Wahab"},
  {q:"The Dark Nightingale nickname?", a:"Abdel Halim Hafez"},
  {q:"Singer of Sawah?", a:"Abdel Halim Hafez"},
  {q:"Composer of Egyptian national anthem?", a:"Sayed Darwish"},
  {q:"Lyricist of Enta Omri?", a:"Ahmed Shafik Kamel"},
  {q:"Egyptian shaabi stars of Bent El Geran?", a:"Hassan Shakosh and Omar Kamal"},
  {q:"Egyptian rock band famous for Salmiya?", a:"Cairokee"},
  {q:"Composer of Al-Mummia film score (1969)?", a:"Mario Nascimbene"}
],
"American Songs & Artists": [
  {q:"King of Rock and Roll?", a:"Elvis Presley"},
  {q:"Artist of 1982 album Thriller?", a:"Michael Jackson"},
  {q:"Singer of Like a Rolling Stone?", a:"Bob Dylan"},
  {q:"Band behind Hotel California?", a:"The Eagles"},
  {q:"Queen of Soul?", a:"Aretha Franklin"},
  {q:"Artist of 2016 album Lemonade?", a:"Beyonce"},
  {q:"Rapper of To Pimp a Butterfly (2015)?", a:"Kendrick Lamar"},
  {q:"Composer of Rhapsody in Blue (1924)?", a:"George Gershwin"},
  {q:"Solo American artist with most #1 hits?", a:"Mariah Carey (19)"},
  {q:"First rap song to hit #1 on Billboard Hot 100?", a:"Rapture by Blondie (1981)"}
],
"Wars": [
  {q:"Years of WWII?", a:"1939-1945"},
  {q:"Cities that atomic bombs were dropped on?", a:"Hiroshima and Nagasaki"},
  {q:"Cold War superpowers?", a:"USA and USSR"},
  {q:"War that included Battle of Gettysburg?", a:"American Civil War"},
  {q:"Archduke whose assassination triggered WWI?", a:"Franz Ferdinand"},
  {q:"Year Vietnam War ended?", a:"1975"},
  {q:"Codename for D-Day invasion of Normandy?", a:"Operation Overlord"},
  {q:"1571 naval battle halting Ottoman expansion?", a:"Battle of Lepanto"},
  {q:"Treaty ending the Thirty Years War?", a:"Peace of Westphalia (1648)"},
  {q:"Carthaginian general who won Battle of Cannae?", a:"Hannibal Barca"}
],
"History": [
  {q:"First US President?", a:"George Washington"},
  {q:"Year Columbus reached the Americas?", a:"1492"},
  {q:"Empire that built the Colosseum?", a:"Roman Empire"},
  {q:"First Emperor of China?", a:"Qin Shi Huang"},
  {q:"Year Magna Carta signed?", a:"1215"},
  {q:"Last Tsar of Russia?", a:"Nicholas II"},
  {q:"Civilization that built Machu Picchu?", a:"Inca"},
  {q:"Pharaoh traditionally linked with the Exodus?", a:"Ramesses II"},
  {q:"Treaty of Tordesillas divided New World between?", a:"Spain and Portugal"},
  {q:"Byzantine Emperor when Constantinople fell (1453)?", a:"Constantine XI Palaiologos"}
],
 "Geography": [
    { q: "What is the capital of France?", a: "Paris", difficulty: 0, hint: "City of light", choices: ["Paris", "Lyon", "Marseille", "Toulouse"] },
    { q: "Which continent is Egypt in?", a: "Africa", difficulty: 0, hint: "Home to the Sahara", choices: ["Africa", "Asia", "Europe", "Middle East"] },
    { q: "What is the longest river in the world?", a: "Nile", difficulty: 0, hint: "Flows through Egypt", choices: ["Nile", "Amazon", "Mississippi", "Yangtze"] },
    { q: "What is the largest ocean?", a: "Pacific Ocean", difficulty: 0, hint: "Between Asia and America", choices: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
    { q: "What is the capital of Japan?", a: "Tokyo", difficulty: 1, hint: "Largest metropolitan area in the world", choices: ["Tokyo", "Kyoto", "Osaka", "Yokohama"] },
    { q: "How many countries are in Africa?", a: "54", difficulty: 1, hint: "Between 50 and 60", choices: ["48", "54", "58", "62"] },
    { q: "What is the smallest country in the world?", a: "Vatican City", difficulty: 1, hint: "Inside Rome", choices: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"] },
    { q: "Which country has the largest population?", a: "India", difficulty: 1, hint: "Surpassed China in 2023", choices: ["India", "China", "United States", "Indonesia"] },
    { q: "What is the highest mountain in Africa?", a: "Mount Kilimanjaro", difficulty: 2, hint: "In Tanzania", choices: ["Mount Kilimanjaro", "Mount Kenya", "Mount Meru", "Mount Stanley"] },
    { q: "What is the capital of Australia?", a: "Canberra", difficulty: 2, hint: "Not Sydney or Melbourne", choices: ["Canberra", "Sydney", "Melbourne", "Brisbane"] },
    { q: "Which country has the most time zones?", a: "France", difficulty: 2, hint: "12 due to overseas territories", choices: ["France", "Russia", "United States", "United Kingdom"] },
    { q: "What is the deepest lake in the world?", a: "Lake Baikal", difficulty: 2, hint: "In Siberia, Russia", choices: ["Lake Baikal", "Lake Tanganyika", "Caspian Sea", "Lake Superior"] },
    { q: "What is the capital of Canada?", a: "Ottawa", difficulty: 3, hint: "Not Toronto or Montreal", choices: ["Ottawa", "Toronto", "Montreal", "Vancouver"] },
    { q: "Which river flows through Baghdad?", a: "Tigris", difficulty: 3, hint: "One of two Mesopotamian rivers", choices: ["Tigris", "Euphrates", "Jordan", "Karun"] },
    { q: "What is the largest desert in the world?", a: "Antarctic Desert", difficulty: 3, hint: "Yes, it counts as a desert", choices: ["Antarctic Desert", "Sahara", "Arabian Desert", "Gobi"] },
    { q: "Which country is known as the Land of the Rising Sun?", a: "Japan", difficulty: 3, hint: "East Asian archipelago", choices: ["Japan", "China", "South Korea", "Philippines"] },
    { q: "What is the largest island in the Mediterranean Sea?", a: "Sicily", difficulty: 3, hint: "Italian island", choices: ["Sicily", "Sardinia", "Cyprus", "Crete"] },
    { q: "What is the capital of Egypt?", a: "Cairo", difficulty: 4, hint: "Largest city in the Arab world", choices: ["Cairo", "Alexandria", "Giza", "Luxor"] },
    { q: "Which country has the longest coastline?", a: "Canada", difficulty: 4, hint: "Bordered by three oceans", choices: ["Canada", "Russia", "Indonesia", "Australia"] },
    { q: "What is the capital of Turkey?", a: "Ankara", difficulty: 4, hint: "Not Istanbul", choices: ["Ankara", "Istanbul", "Izmir", "Bursa"] },
    { q: "Which strait separates Europe from Africa?", a: "Strait of Gibraltar", difficulty: 4, hint: "Named after a British territory", choices: ["Strait of Gibraltar", "Bosphorus", "Dardanelles", "Strait of Sicily"] },
    { q: "What is the second-largest country by land area?", a: "Canada", difficulty: 4, hint: "North American country", choices: ["Canada", "China", "United States", "Brazil"] },
    { q: "Which river is the longest in Europe?", a: "Volga", difficulty: 5, hint: "Flows entirely through Russia", choices: ["Volga", "Danube", "Rhine", "Dnieper"] },
    { q: "What is the highest capital city in the world?", a: "La Paz", difficulty: 5, hint: "In Bolivia, over 3,600m elevation", choices: ["La Paz", "Quito", "Bogota", "Kathmandu"] },
    { q: "Which country has the most islands?", a: "Sweden", difficulty: 5, hint: "Over 267,000 islands, Scandinavian", choices: ["Sweden", "Finland", "Indonesia", "Philippines"] },
    { q: "Which is the only country to border both the Atlantic and Indian Oceans?", a: "South Africa", difficulty: 5, hint: "Southern tip of Africa", choices: ["South Africa", "Egypt", "Morocco", "Mozambique"] },
    { q: "Which sea is the saltiest natural body of water?", a: "Don Juan Pond", difficulty: 5, hint: "Actually a pond in Antarctica, saltier than Dead Sea", choices: ["Don Juan Pond", "Dead Sea", "Lake Assal", "Great Salt Lake"] },
    { q: "What is the capital of Kazakhstan (as of 2019)?", a: "Astana", difficulty: 6, hint: "Renamed briefly to Nur-Sultan, then back", choices: ["Astana", "Almaty", "Shymkent", "Karaganda"] },
    { q: "Which country is the least densely populated?", a: "Mongolia", difficulty: 6, hint: "Central Asian country between Russia and China", choices: ["Mongolia", "Iceland", "Australia", "Namibia"] },
    { q: "What is the northernmost capital city of an independent country?", a: "Reykjavik", difficulty: 6, hint: "Iceland", choices: ["Reykjavik", "Helsinki", "Oslo", "Nuuk"] },
    { q: "What is the largest landlocked country?", a: "Kazakhstan", difficulty: 6, hint: "Central Asian country", choices: ["Kazakhstan", "Mongolia", "Chad", "Afghanistan"] },
    { q: "Which African country was formerly known as Abyssinia?", a: "Ethiopia", difficulty: 6, hint: "Horn of Africa", choices: ["Ethiopia", "Eritrea", "Sudan", "Somalia"] },
    { q: "What is the deepest point in the ocean called?", a: "Challenger Deep", difficulty: 7, hint: "In the Mariana Trench", choices: ["Challenger Deep", "Tonga Trench", "Java Trench", "Puerto Rico Trench"] },
    { q: "Which country has the most UNESCO World Heritage sites (as of 2024)?", a: "Italy", difficulty: 7, hint: "60 sites, European country", choices: ["Italy", "China", "Germany", "Spain"] },
    { q: "Which river forms the border between Mexico and the US in Texas?", a: "Rio Grande", difficulty: 7, hint: "Also called Rio Bravo in Mexico", choices: ["Rio Grande", "Colorado", "Pecos", "Nueces"] },
    { q: "What is the smallest ocean by area?", a: "Arctic Ocean", difficulty: 7, hint: "Around the North Pole", choices: ["Arctic Ocean", "Southern Ocean", "Indian Ocean", "Atlantic Ocean"] },
    { q: "Which country has three capital cities?", a: "South Africa", difficulty: 7, hint: "Pretoria, Cape Town, Bloemfontein", choices: ["South Africa", "Netherlands", "Bolivia", "Sri Lanka"] },
    { q: "What is the highest waterfall in the world?", a: "Angel Falls", difficulty: 8, hint: "Located in Venezuela", choices: ["Angel Falls", "Tugela Falls", "Yosemite Falls", "Victoria Falls"] },
    { q: "Which country is entirely surrounded by South Africa?", a: "Lesotho", difficulty: 8, hint: "Kingdom in the mountains", choices: ["Lesotho", "Swaziland", "Botswana", "Namibia"] },
    { q: "Which is the only country name that starts with the letter O?", a: "Oman", difficulty: 8, hint: "Arabian Peninsula", choices: ["Oman", "Nowhere", "Actually there are others", "Only one"] },
    { q: "What is the longest mountain range in the world?", a: "Andes", difficulty: 8, hint: "Runs along western South America", choices: ["Andes", "Rocky Mountains", "Himalayas", "Great Dividing Range"] },
    { q: "What is the largest freshwater lake by volume?", a: "Lake Baikal", difficulty: 8, hint: "Russian lake also deepest", choices: ["Lake Baikal", "Lake Superior", "Lake Tanganyika", "Lake Victoria"] },
    { q: "Which country is the only one to lie on all four hemispheres?", a: "Kiribati", difficulty: 9, hint: "Pacific island nation", choices: ["Kiribati", "Indonesia", "Ecuador", "Colombia"] },
    { q: "What is the lowest point on Earth's dry land surface?", a: "Dead Sea shore", difficulty: 9, hint: "About 430m below sea level", choices: ["Dead Sea shore", "Denakil Depression", "Lake Assal", "Turpan Depression"] },
    { q: "Which African country has the most pyramids?", a: "Sudan", difficulty: 9, hint: "More than Egypt, over 200", choices: ["Sudan", "Egypt", "Libya", "Ethiopia"] },
    { q: "What was the former name of the country now called Myanmar until 1989?", a: "Burma", difficulty: 9, hint: "Southeast Asian country", choices: ["Burma", "Siam", "Ceylon", "Formosa"] },
    { q: "What is the only US state capital with no letters in common with the state name?", a: "Pierre", difficulty: 9, hint: "Capital of South Dakota", choices: ["Pierre", "Dover", "Augusta", "Frankfort"] }
  ],
"Biology": [
  {q:"Powerhouse of the cell?", a:"Mitochondria"},
  {q:"Largest human organ?", a:"Skin"},
  {q:"Molecule carrying genetic info?", a:"DNA"},
  {q:"Chambers in human heart?", a:"4"},
  {q:"Cells that fight infection?", a:"White blood cells"},
  {q:"Process plants use to make food?", a:"Photosynthesis"},
  {q:"Father of modern genetics?", a:"Gregor Mendel"},
  {q:"Neuron part receiving signals?", a:"Dendrites"},
  {q:"Enzyme that unwinds DNA?", a:"Helicase"},
  {q:"Cycle producing ATP in mitochondria?", a:"Krebs Cycle"}
],
"Chemistry": [
  {q:"Symbol for water?", a:"H2O"},
  {q:"Atomic number of Carbon?", a:"6"},
  {q:"Gas plants absorb?", a:"CO2"},
  {q:"pH of pure water?", a:"7"},
  {q:"Creator of modern periodic table?", a:"Dmitri Mendeleev"},
  {q:"Most abundant gas in atmosphere?", a:"Nitrogen"},
  {q:"Avogadros number?", a:"6.02 x 10^23"},
  {q:"Bond by sharing electrons?", a:"Covalent"},
  {q:"Element with highest electronegativity?", a:"Fluorine"},
  {q:"IUPAC name for CH3COOH?", a:"Ethanoic acid"}
],
"Physics": [
  {q:"SI unit of force?", a:"Newton"},
  {q:"Mass-energy equivalence formula?", a:"E = mc^2"},
  {q:"Speed of light (approx)?", a:"3 x 10^8 m/s"},
  {q:"Who formulated the three laws of motion?", a:"Isaac Newton"},
  {q:"Unit of electric current?", a:"Ampere"},
  {q:"Particle carrying electromagnetic force?", a:"Photon"},
  {q:"Plancks constant?", a:"6.63 x 10^-34 J.s"},
  {q:"Effect of frequency change due to motion?", a:"Doppler Effect"},
  {q:"Principle: cant know position and momentum precisely?", a:"Heisenberg Uncertainty"},
  {q:"Geometric spacetime property caused by mass?", a:"Curvature"}
],
"Logos": [
  {q:"Red script wordmark, fizzy dark drink?", a:"Coca-Cola"},
  {q:"Silver bitten fruit?", a:"Apple"},
  {q:"Yellow M arch?", a:"McDonalds"},
  {q:"Blue bird (now X)?", a:"Twitter/X"},
  {q:"Red bullseye retail?", a:"Target"},
  {q:"Checkmark swoosh?", a:"Nike"},
  {q:"Two interlocking Cs, French luxury?", a:"Chanel"},
  {q:"Three stripes sportswear?", a:"Adidas"},
  {q:"Prancing horse on yellow shield?", a:"Ferrari"},
  {q:"Blue oval script, American automaker?", a:"Ford"}
],
"Food Cuisine": [
  {q:"Pizzas origin country?", a:"Italy"},
  {q:"Main ingredient in guacamole?", a:"Avocado"},
  {q:"Sushis origin?", a:"Japan"},
  {q:"Egyptian dish of rice, lentils, pasta, tomato sauce?", a:"Koshari"},
  {q:"Most expensive spice by weight?", a:"Saffron"},
  {q:"Cheese on Margherita pizza?", a:"Mozzarella"},
  {q:"Mole sauce is from?", a:"Mexico"},
  {q:"Key ingredient in bouillabaisse?", a:"Fish"},
  {q:"Japanese dried bonito flakes name?", a:"Katsuobushi"},
  {q:"French mother sauce of milk and white roux?", a:"Bechamel"}
],
"Mathematics": [
  {q:"15 x 12?", a:"180"},
  {q:"Pi to 2 decimals?", a:"3.14"},
  {q:"Square root of 169?", a:"13"},
  {q:"Sum of interior angles of a triangle?", a:"180 degrees"},
  {q:"Derivative of x^2?", a:"2x"},
  {q:"Eulers number to 3 decimals?", a:"2.718"},
  {q:"Integral of 1/x dx?", a:"ln|x| + C"},
  {q:"Faces on an icosahedron?", a:"20"},
  {q:"Smallest prime greater than 100?", a:"101"},
  {q:"Golden ratio to 3 decimals?", a:"1.618"}
],
"Arabic Nahw": [
  {q:"Parts of speech in Arabic?", a:"Ism, Fil, Harf"},
  {q:"Sign of raf for singular noun?", a:"Damma"},
  {q:"Sign of nasb for muthanna?", a:"Ya"},
  {q:"What are Al-Afal Al-Khamsa?", a:"Mudari verbs with alif ithnain, waw jamaa, or ya mukhataba"},
  {q:"Irab of Muhammadun in Muhammadun mujtahidun?", a:"Mubtada marfu, alamatuhu al-damma"},
  {q:"Number of huruf jarr?", a:"20"},
  {q:"Difference between kaana and inna in amal?", a:"Kaana raises ism, nasb khabar; inna nasb ism, raises khabar"},
  {q:"What is mamnu min al-sarf?", a:"Noun that doesnt accept tanwin or kasra"},
  {q:"Irab of lawla in nominal sentence?", a:"Harf imtinaa li-wujud"},
  {q:"Definition of Hal?", a:"Wasf fadla mansub bayyin hayat sahibihi"}
],
 "TV Shows": [
    { q: "What is the name of the coffee shop in Friends?", a: "Central Perk", difficulty: 0, hint: "Play on Central Park", choices: ["Central Perk", "Java Joe's", "The Grind", "Cafe Nervosa"] },
    { q: "What is the setting of Breaking Bad?", a: "Albuquerque", difficulty: 0, hint: "City in New Mexico", choices: ["Albuquerque", "Phoenix", "El Paso", "Santa Fe"] },
    { q: "Who is the main character in The Office (US)?", a: "Michael Scott", difficulty: 0, hint: "Played by Steve Carell", choices: ["Michael Scott", "Jim Halpert", "Dwight Schrute", "Andy Bernard"] },
    { q: "What house does Jon Snow belong to in Game of Thrones?", a: "Stark", difficulty: 0, hint: "Winter is coming family", choices: ["Stark", "Targaryen", "Lannister", "Baratheon"] },
    { q: "What is the profession of Ted Mosby in How I Met Your Mother?", a: "Architect", difficulty: 1, hint: "Designs buildings", choices: ["Architect", "Lawyer", "Teacher", "Doctor"] },
    { q: "In Stranger Things, what is the alternate dimension called?", a: "The Upside Down", difficulty: 1, hint: "Reversed word", choices: ["The Upside Down", "The Void", "The Otherworld", "The Underside"] },
    { q: "Who plays Sherlock in the BBC series Sherlock?", a: "Benedict Cumberbatch", difficulty: 1, hint: "Also plays Doctor Strange", choices: ["Benedict Cumberbatch", "Martin Freeman", "Andrew Scott", "Tom Hiddleston"] },
    { q: "What year did The Simpsons first air as its own show?", a: "1989", difficulty: 1, hint: "Late 1980s", choices: ["1987", "1989", "1991", "1993"] },
    { q: "What was the profession of Don Draper in Mad Men?", a: "Advertising executive", difficulty: 2, hint: "Madison Avenue in the 1960s", choices: ["Advertising executive", "Lawyer", "Journalist", "Politician"] },
    { q: "What is the name of the ship in Star Trek: The Next Generation?", a: "USS Enterprise-D", difficulty: 2, hint: "Captain Picard's ship", choices: ["USS Enterprise-D", "USS Voyager", "USS Defiant", "USS Discovery"] },
    { q: "Who created The Wire?", a: "David Simon", difficulty: 2, hint: "Former Baltimore Sun reporter", choices: ["David Simon", "David Chase", "Vince Gilligan", "Matthew Weiner"] },
    { q: "In what year did Seinfeld air its final episode?", a: "1998", difficulty: 2, hint: "Late 1990s", choices: ["1996", "1998", "2000", "2002"] },
    { q: "Who directed the pilot of Lost?", a: "J.J. Abrams", difficulty: 3, hint: "Also directed Star Wars: The Force Awakens", choices: ["J.J. Abrams", "Damon Lindelof", "Carlton Cuse", "Bryan Burk"] },
    { q: "What is the last name of Fox Mulder's partner in The X-Files?", a: "Scully", difficulty: 3, hint: "Dana...", choices: ["Scully", "Reyes", "Doggett", "Skinner"] },
    { q: "How many seasons of The Sopranos are there?", a: "6", difficulty: 3, hint: "Split final season", choices: ["5", "6", "7", "8"] },
    { q: "What network aired the original run of Twin Peaks?", a: "ABC", difficulty: 3, hint: "One of the Big Three US networks", choices: ["ABC", "NBC", "CBS", "Fox"] },
    { q: "Who plays Saul Goodman in Breaking Bad and Better Call Saul?", a: "Bob Odenkirk", difficulty: 3, hint: "Also does comedy", choices: ["Bob Odenkirk", "Aaron Paul", "Giancarlo Esposito", "Jonathan Banks"] },
    { q: "What year did The Sopranos first air?", a: "1999", difficulty: 4, hint: "End of the 1990s on HBO", choices: ["1997", "1999", "2001", "2003"] },
    { q: "Who created Twin Peaks with Mark Frost?", a: "David Lynch", difficulty: 4, hint: "Surrealist filmmaker", choices: ["David Lynch", "David Chase", "Chris Carter", "Damon Lindelof"] },
    { q: "How many episodes of The Wire are there in total?", a: "60", difficulty: 4, hint: "5 seasons average 12 episodes each", choices: ["55", "60", "65", "70"] },
    { q: "Who created Deadwood?", a: "David Milch", difficulty: 4, hint: "Also worked on NYPD Blue", choices: ["David Milch", "David Chase", "David Simon", "David Benioff"] },
    { q: "What was the first show to win the Primetime Emmy for Outstanding Drama Series more than once?", a: "The Defenders", difficulty: 5, hint: "1960s legal drama", choices: ["The Defenders", "Playhouse 90", "Gunsmoke", "Robert Montgomery Presents"] },
    { q: "Who directed the pilot of The Sopranos?", a: "David Chase", difficulty: 5, hint: "Also created the show", choices: ["David Chase", "Tim Van Patten", "Alan Taylor", "Allen Coulter"] },
    { q: "What was the highest-rated TV finale ever in US history?", a: "M*A*S*H", difficulty: 5, hint: "1983 Korean War comedy finale", choices: ["M*A*S*H", "Seinfeld", "Friends", "Cheers"] },
    { q: "How many episodes did The Twilight Zone (original) have?", a: "156", difficulty: 5, hint: "Between 150 and 160", choices: ["132", "156", "178", "192"] },
    { q: "Who created Curb Your Enthusiasm?", a: "Larry David", difficulty: 5, hint: "Also co-created Seinfeld", choices: ["Larry David", "Jerry Seinfeld", "Bob Odenkirk", "Judd Apatow"] },
    { q: "What year did Doctor Who first air?", a: "1963", difficulty: 6, hint: "Same year JFK was assassinated", choices: ["1961", "1963", "1965", "1967"] },
    { q: "Who was the first actor to play Doctor Who?", a: "William Hartnell", difficulty: 6, hint: "1963-1966", choices: ["William Hartnell", "Patrick Troughton", "Jon Pertwee", "Tom Baker"] },
    { q: "What was the first cable series to win the Emmy for Outstanding Drama Series?", a: "The Sopranos", difficulty: 6, hint: "HBO landmark win in 2004", choices: ["The Sopranos", "The Wire", "Six Feet Under", "Deadwood"] },
    { q: "Who created The Twilight Zone?", a: "Rod Serling", difficulty: 6, hint: "Also served as its host", choices: ["Rod Serling", "Alfred Hitchcock", "Gene Roddenberry", "Ray Bradbury"] },
    { q: "What show did Norman Lear create that ran from 1971 to 1979?", a: "All in the Family", difficulty: 6, hint: "Archie Bunker", choices: ["All in the Family", "The Jeffersons", "Sanford and Son", "Maude"] },
    { q: "What was the first TV show broadcast in color in the US?", a: "The Marriage", difficulty: 7, hint: "1954 NBC series", choices: ["The Marriage", "Bonanza", "The Jack Benny Show", "The Ed Sullivan Show"] },
    { q: "Who created the original British version of The Office?", a: "Ricky Gervais and Stephen Merchant", difficulty: 7, hint: "Also collaborated on Extras", choices: ["Ricky Gervais and Stephen Merchant", "Sacha Baron Cohen and Dan Mazer", "Steve Coogan and Peter Baynham", "Armando Iannucci and Chris Morris"] },
    { q: "What was the first Netflix original scripted series?", a: "Lilyhammer", difficulty: 7, hint: "Steven Van Zandt starring, released 2012", choices: ["Lilyhammer", "House of Cards", "Orange Is the New Black", "Hemlock Grove"] },
    { q: "Who wrote the pilot episode of Cheers?", a: "Glen and Les Charles", difficulty: 7, hint: "Twin brothers, also created the show with James Burrows", choices: ["Glen and Les Charles", "James Burrows", "David Angell", "Ken Levine"] },
    { q: "What year did The Ed Sullivan Show end?", a: "1971", difficulty: 7, hint: "Early 1970s", choices: ["1969", "1971", "1973", "1975"] },
    { q: "Who directed the Battle of the Bastards episode of Game of Thrones?", a: "Miguel Sapochnik", difficulty: 8, hint: "Also directed Hardhome and Winds of Winter", choices: ["Miguel Sapochnik", "Alan Taylor", "David Nutter", "Neil Marshall"] },
    { q: "What was the first show to be officially called a 'series' on television in the modern sense?", a: "Faraway Hill", difficulty: 8, hint: "1946 DuMont soap opera", choices: ["Faraway Hill", "Kraft Television Theatre", "Texaco Star Theater", "Meet the Press"] },
    { q: "Who created Six Feet Under?", a: "Alan Ball", difficulty: 8, hint: "Also wrote American Beauty", choices: ["Alan Ball", "David Chase", "David Simon", "Ronald D. Moore"] },
    { q: "What was the last episode of The Sopranos called?", a: "Made in America", difficulty: 8, hint: "Series finale, June 2007", choices: ["Made in America", "The Blue Comet", "Kennedy and Heidi", "Chasing It"] },
    { q: "Who composed the theme for The X-Files?", a: "Mark Snow", difficulty: 8, hint: "Iconic whistling melody", choices: ["Mark Snow", "Danny Elfman", "Angelo Badalamenti", "W.G. Snuffy Walden"] },
    { q: "Who was the showrunner for the final two seasons of Mad Men?", a: "Matthew Weiner", difficulty: 9, hint: "Also created the show", choices: ["Matthew Weiner", "Andre Jacquemetton", "Semi Chellas", "Jonathan Igla"] },
    { q: "In what year was the first color TV broadcast license granted by the FCC in the US?", a: "1950", difficulty: 9, hint: "CBS system, mid-20th century", choices: ["1946", "1950", "1953", "1956"] },
    { q: "Who directed the episode 'Ozymandias' of Breaking Bad?", a: "Rian Johnson", difficulty: 9, hint: "Also directed Knives Out and The Last Jedi", choices: ["Rian Johnson", "Vince Gilligan", "Michelle MacLaren", "Adam Bernstein"] },
    { q: "What was the first non-English language show to win a Primetime Emmy for Outstanding Drama Series?", a: "None yet", difficulty: 9, hint: "Even Squid Game won a different category (limited series or drama)", choices: ["None yet", "Squid Game", "Money Heist", "Dark"] },
    { q: "Who created The Prisoner (1967)?", a: "Patrick McGoohan", difficulty: 9, hint: "Also starred as Number Six", choices: ["Patrick McGoohan", "George Markstein", "Lew Grade", "David McCallum"] }
  ],
 "Movies": [
    { q: "Who directed the 1994 film 'Pulp Fiction'?", a: "Quentin Tarantino", difficulty: 0, hint: "Known for nonlinear storytelling and pop culture references", choices: ["Quentin Tarantino", "Martin Scorsese", "David Fincher", "Paul Thomas Anderson"] },
    { q: "What year was the first Toy Story film released?", a: "1995", difficulty: 0, hint: "Mid-1990s Pixar debut", choices: ["1993", "1995", "1997", "1999"] },
    { q: "Who played Jack in Titanic (1997)?", a: "Leonardo DiCaprio", difficulty: 0, hint: "Later won an Oscar for The Revenant", choices: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Ben Affleck"] },
    { q: "What is the highest-grossing film of all time (as of 2024)?", a: "Avatar", difficulty: 0, hint: "James Cameron blue aliens", choices: ["Avatar", "Avengers Endgame", "Titanic", "Star Wars The Force Awakens"] },
    { q: "Who directed Inception?", a: "Christopher Nolan", difficulty: 1, hint: "Also directed The Dark Knight trilogy", choices: ["Christopher Nolan", "Denis Villeneuve", "Ridley Scott", "Steven Spielberg"] },
    { q: "What year did The Godfather come out?", a: "1972", difficulty: 1, hint: "Early 1970s Coppola classic", choices: ["1970", "1972", "1974", "1976"] },
    { q: "Who played the Joker in The Dark Knight (2008)?", a: "Heath Ledger", difficulty: 1, hint: "Won a posthumous Oscar", choices: ["Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Jack Nicholson"] },
    { q: "What is the name of the wizarding school in Harry Potter?", a: "Hogwarts", difficulty: 1, hint: "Founded by four wizards", choices: ["Hogwarts", "Ilvermorny", "Beauxbatons", "Durmstrang"] },
    { q: "Who directed Jaws (1975)?", a: "Steven Spielberg", difficulty: 1, hint: "Also directed E.T. and Jurassic Park", choices: ["Steven Spielberg", "George Lucas", "Francis Ford Coppola", "Martin Scorsese"] },
    { q: "In which year was Casablanca released?", a: "1942", difficulty: 2, hint: "During World War II", choices: ["1939", "1942", "1945", "1948"] },
    { q: "Who directed 2001: A Space Odyssey?", a: "Stanley Kubrick", difficulty: 2, hint: "Also directed The Shining", choices: ["Stanley Kubrick", "Ridley Scott", "George Lucas", "Steven Spielberg"] },
    { q: "Which film won Best Picture at the 2020 Oscars?", a: "Parasite", difficulty: 2, hint: "First non-English language film to win Best Picture", choices: ["Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"] },
    { q: "Who composed the score for Star Wars?", a: "John Williams", difficulty: 2, hint: "Also composed Indiana Jones and Jurassic Park themes", choices: ["John Williams", "Hans Zimmer", "James Horner", "Ennio Morricone"] },
    { q: "What is the name of Rick's cafe in Casablanca?", a: "Rick's Cafe Americain", difficulty: 3, hint: "Named after the protagonist with American in it", choices: ["Rick's Cafe Americain", "Rick's Place", "The Blue Parrot", "Cafe Casablanca"] },
    { q: "Who directed Citizen Kane?", a: "Orson Welles", difficulty: 3, hint: "He also starred in it as the title character", choices: ["Orson Welles", "Alfred Hitchcock", "John Ford", "Frank Capra"] },
    { q: "What was the first feature-length animated film?", a: "Snow White and the Seven Dwarfs", difficulty: 3, hint: "Disney 1937", choices: ["Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Bambi"] },
    { q: "Who directed the original Alien (1979)?", a: "Ridley Scott", difficulty: 3, hint: "Also directed Blade Runner and Gladiator", choices: ["Ridley Scott", "James Cameron", "John Carpenter", "David Fincher"] },
    { q: "What year was the first Godfather film released?", a: "1972", difficulty: 3, hint: "Won Best Picture", choices: ["1970", "1972", "1974", "1976"] },
    { q: "Which film won Best Picture in 1994?", a: "Forrest Gump", difficulty: 4, hint: "Tom Hanks starring", choices: ["Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "Four Weddings and a Funeral"] },
    { q: "Who was the youngest actor to win Best Actor Oscar?", a: "Adrien Brody", difficulty: 4, hint: "Won for The Pianist at age 29", choices: ["Adrien Brody", "Marlon Brando", "Leonardo DiCaprio", "Timothee Chalamet"] },
    { q: "What is the highest-grossing R-rated film of all time?", a: "Deadpool & Wolverine", difficulty: 4, hint: "2024 Marvel release", choices: ["Deadpool & Wolverine", "Joker", "Oppenheimer", "The Passion of the Christ"] },
    { q: "Who directed There Will Be Blood?", a: "Paul Thomas Anderson", difficulty: 4, hint: "Also directed Magnolia and Boogie Nights", choices: ["Paul Thomas Anderson", "Wes Anderson", "The Coen Brothers", "David Fincher"] },
    { q: "What was the first film to gross over \$2 billion?", a: "Avatar", difficulty: 4, hint: "2009 James Cameron film", choices: ["Avatar", "Titanic", "Avengers Infinity War", "Star Wars The Force Awakens"] },
    { q: "Who directed Seven Samurai (1954)?", a: "Akira Kurosawa", difficulty: 5, hint: "Legendary Japanese filmmaker", choices: ["Akira Kurosawa", "Yasujiro Ozu", "Hayao Miyazaki", "Kenji Mizoguchi"] },
    { q: "What was Alfred Hitchcock's first film?", a: "The Pleasure Garden", difficulty: 5, hint: "1925 silent film", choices: ["The Pleasure Garden", "The Lodger", "Blackmail", "Number 13"] },
    { q: "Which director has won the most Best Director Oscars?", a: "John Ford", difficulty: 5, hint: "Won 4 times, known for westerns", choices: ["John Ford", "Frank Capra", "William Wyler", "Steven Spielberg"] },
    { q: "Who played the title role in Lawrence of Arabia?", a: "Peter O'Toole", difficulty: 5, hint: "Irish actor, first major role", choices: ["Peter O'Toole", "Richard Burton", "Alec Guinness", "Omar Sharif"] },
    { q: "What film features the line 'Rosebud'?", a: "Citizen Kane", difficulty: 5, hint: "Famous ambiguous ending word", choices: ["Citizen Kane", "The Third Man", "Sunset Boulevard", "All About Eve"] },
    { q: "Who directed 8 1/2 (1963)?", a: "Federico Fellini", difficulty: 6, hint: "Italian director of La Dolce Vita", choices: ["Federico Fellini", "Michelangelo Antonioni", "Vittorio De Sica", "Luchino Visconti"] },
    { q: "What was the first film to win all Big Five Oscars?", a: "It Happened One Night", difficulty: 6, hint: "1934 Frank Capra comedy", choices: ["It Happened One Night", "Gone with the Wind", "Casablanca", "Mrs. Miniver"] },
    { q: "Who directed The 400 Blows (1959)?", a: "Francois Truffaut", difficulty: 6, hint: "French New Wave founder", choices: ["Francois Truffaut", "Jean-Luc Godard", "Eric Rohmer", "Claude Chabrol"] },
    { q: "In what year did the Academy Awards begin?", a: "1929", difficulty: 6, hint: "Late 1920s", choices: ["1925", "1927", "1929", "1931"] },
    { q: "Who was the first African American to win Best Actor Oscar?", a: "Sidney Poitier", difficulty: 6, hint: "Won for Lilies of the Field (1963)", choices: ["Sidney Poitier", "Denzel Washington", "Jamie Foxx", "Forest Whitaker"] },
    { q: "Which film has the most Oscar wins ever (tied)?", a: "Ben-Hur", difficulty: 7, hint: "1959 epic, tied with Titanic and Lord of the Rings Return of the King at 11", choices: ["Ben-Hur", "Gone with the Wind", "West Side Story", "Gandhi"] },
    { q: "Who directed Persona (1966)?", a: "Ingmar Bergman", difficulty: 7, hint: "Swedish master filmmaker", choices: ["Ingmar Bergman", "Carl Theodor Dreyer", "Roy Andersson", "Lars von Trier"] },
    { q: "What was the highest-grossing silent film?", a: "The Big Parade", difficulty: 7, hint: "1925 King Vidor war film", choices: ["The Big Parade", "Birth of a Nation", "The Kid", "The Gold Rush"] },
    { q: "Who was the first female director nominated for a Best Director Oscar?", a: "Lina Wertmuller", difficulty: 7, hint: "Italian director nominated in 1977 for Seven Beauties", choices: ["Lina Wertmuller", "Sofia Coppola", "Jane Campion", "Kathryn Bigelow"] },
    { q: "In what year was the first Cannes Film Festival held?", a: "1946", difficulty: 7, hint: "Just after WWII", choices: ["1939", "1946", "1949", "1952"] },
    { q: "Who directed Tokyo Story (1953)?", a: "Yasujiro Ozu", difficulty: 8, hint: "Japanese master of family drama", choices: ["Yasujiro Ozu", "Akira Kurosawa", "Kenji Mizoguchi", "Mikio Naruse"] },
    { q: "What was the first film to use synchronized sound dialogue?", a: "The Jazz Singer", difficulty: 8, hint: "1927 Warner Bros. release", choices: ["The Jazz Singer", "Don Juan", "Steamboat Willie", "Lights of New York"] },
    { q: "Who won the first ever Best Actress Oscar?", a: "Janet Gaynor", difficulty: 8, hint: "Won for three films at the 1929 ceremony", choices: ["Janet Gaynor", "Mary Pickford", "Norma Shearer", "Louise Dresser"] },
    { q: "Which film was Sergei Eisenstein's debut feature?", a: "Strike", difficulty: 8, hint: "1925 Soviet montage film about a factory strike", choices: ["Strike", "Battleship Potemkin", "October", "Alexander Nevsky"] },
    { q: "Who was the cinematographer for Blade Runner (1982)?", a: "Jordan Cronenweth", difficulty: 8, hint: "Known for using smoke and neon", choices: ["Jordan Cronenweth", "Vittorio Storaro", "Roger Deakins", "Gordon Willis"] },
    { q: "What was the first film shot entirely with a smartphone to be released theatrically?", a: "Tangerine", difficulty: 9, hint: "2015 Sean Baker film shot on iPhone 5S", choices: ["Tangerine", "Unsane", "High Flying Bird", "Searching"] },
    { q: "Who edited Raging Bull (1980)?", a: "Thelma Schoonmaker", difficulty: 9, hint: "Longtime Scorsese collaborator, won Oscar for this film", choices: ["Thelma Schoonmaker", "Anne V. Coates", "Verna Fields", "Dede Allen"] },
    { q: "What was Yasujiro Ozu's final film?", a: "An Autumn Afternoon", difficulty: 9, hint: "Released 1962, year before his death", choices: ["An Autumn Afternoon", "Late Autumn", "The End of Summer", "Good Morning"] },
    { q: "Who invented the Steadicam?", a: "Garrett Brown", difficulty: 9, hint: "Camera operator who patented it in 1975", choices: ["Garrett Brown", "Vilmos Zsigmond", "Haskell Wexler", "Owen Roizman"] },
    { q: "What is the shortest film to win an Academy Award for Best Picture?", a: "Marty", difficulty: 9, hint: "1955 film, 91 minutes", choices: ["Marty", "Annie Hall", "Rocky", "It Happened One Night"] },
    { q: "Who was the first director to win consecutive Best Director Oscars?", a: "John Ford", difficulty: 9, hint: "Won for Grapes of Wrath (1940) and How Green Was My Valley (1941)", choices: ["John Ford", "Frank Capra", "Joseph L. Mankiewicz", "William Wyler"] }
  ],
"Celebrities": [
  {q:"Founder of Tesla and SpaceX?", a:"Elon Musk"},
  {q:"Beyonces husband?", a:"Jay-Z"},
  {q:"MCU Iron Man actor?", a:"Robert Downey Jr."},
  {q:"Host of long-running Ellen show?", a:"Ellen DeGeneres"},
  {q:"Youngest Kardashian-Jenner sister?", a:"Kylie Jenner"},
  {q:"Queen Bey?", a:"Beyonce"},
  {q:"Best Actor for Bohemian Rhapsody?", a:"Rami Malek"},
  {q:"Rihannas beauty brand?", a:"Fenty Beauty"},
  {q:"Kim Kardashians rapper ex-husband?", a:"Kanye West"},
  {q:"Best Actress for Everything Everywhere All at Once?", a:"Michelle Yeoh"}
],
"Pop Culture": [
  {q:"App known for short vertical videos?", a:"TikTok"},
  {q:"Viral 2015 blue/black vs white/gold item?", a:"The Dress"},
  {q:"Sound effect popularized in Star Wars films?", a:"Wilhelm Scream"},
  {q:"K-pop group behind Dynamite (2020)?", a:"BTS"},
  {q:"Grumpy Cats real name?", a:"Tardar Sauce"},
  {q:"Year Gangnam Style hit 1B YouTube views?", a:"2012"},
  {q:"Family from Keeping Up With?", a:"The Kardashians"},
  {q:"Ice water challenge for ALS?", a:"Ice Bucket Challenge (2014)"},
  {q:"2016 AR mobile game hit?", a:"Pokemon GO"},
  {q:"Viral 2024 pygmy hippo at Thai zoo?", a:"Moo Deng"}
],
"Football": [
  {q:"Players per team on field?", a:"11"},
  {q:"Length of a match?", a:"90 minutes"},
  {q:"Most FIFA World Cup wins?", a:"Brazil (5)"},
  {q:"All-time top mens international scorer?", a:"Cristiano Ronaldo"},
  {q:"Year FIFA founded?", a:"1904"},
  {q:"Most Ballon dOr awards?", a:"Lionel Messi (8)"},
  {q:"First European Cup winner (1956)?", a:"Real Madrid"},
  {q:"Hand of God scorer (1986)?", a:"Diego Maradona"},
  {q:"Oldest club still existing?", a:"Sheffield F.C. (1857)"},
  {q:"First African Ballon dOr winner?", a:"George Weah (1995)"}
],
"English Premier League": [
  {q:"Year Premier League started?", a:"1992"},
  {q:"Most PL titles?", a:"Manchester United (13)"},
  {q:"All-time PL top scorer?", a:"Alan Shearer (260)"},
  {q:"Underdog champions 2015-16?", a:"Leicester City"},
  {q:"Manager of Arsenal Invincibles?", a:"Arsene Wenger"},
  {q:"Teams in the PL?", a:"20"},
  {q:"First to score 100 PL goals for two clubs?", a:"Andy Cole"},
  {q:"2024-25 PL champions?", a:"Liverpool"},
  {q:"Most PL assists ever?", a:"Ryan Giggs (162)"},
  {q:"Fastest PL goal ever?", a:"Shane Long (7.69s, 2019)"}
],
"La Liga": [
  {q:"Teams in La Liga?", a:"20"},
  {q:"Most La Liga titles?", a:"Real Madrid"},
  {q:"Real Madrid vs Barcelona is called?", a:"El Clasico"},
  {q:"All-time La Liga top scorer?", a:"Lionel Messi (474)"},
  {q:"Basque club with Basque-only policy?", a:"Athletic Bilbao"},
  {q:"2020-21 La Liga winner?", a:"Atletico Madrid"},
  {q:"Year La Liga founded?", a:"1929"},
  {q:"Most El Clasico goals?", a:"Lionel Messi (26)"},
  {q:"Clubs never relegated from La Liga?", a:"Real Madrid, Barcelona, Athletic Bilbao"},
  {q:"2023-24 Pichichi winner?", a:"Artem Dovbyk"}
],
"Messi": [
  {q:"National team?", a:"Argentina"},
  {q:"Club he spent most of his career?", a:"FC Barcelona"},
  {q:"Ballon dOr count?", a:"8"},
  {q:"Year he won the World Cup?", a:"2022"},
  {q:"Childhood condition?", a:"GHD (Growth Hormone Deficiency)"},
  {q:"Club after Barcelona (2021)?", a:"PSG"},
  {q:"MLS club joined in 2023?", a:"Inter Miami"},
  {q:"Team he scored first Barca goal against (2005)?", a:"Albacete"},
  {q:"Year he won his first Copa America?", a:"2021"},
  {q:"La Liga goals in record 2011-12 season?", a:"50"}
],
"Cristiano Ronaldo": [
  {q:"National team?", a:"Portugal"},
  {q:"Club he joined in 2003?", a:"Manchester United"},
  {q:"Ballon dOr count?", a:"5"},
  {q:"Club after Real Madrid (2018)?", a:"Juventus"},
  {q:"Saudi club he joined in 2023?", a:"Al-Nassr"},
  {q:"Portuguese island hes from?", a:"Madeira"},
  {q:"Champions League titles?", a:"5"},
  {q:"Year he won Euro with Portugal?", a:"2016"},
  {q:"His signature free-kick style?", a:"Knuckleball"},
  {q:"Transfer fee to Real Madrid (2009)?", a:"80 million pounds"}
],
"Console Games": [
  {q:"Maker of PlayStation?", a:"Sony"},
  {q:"Maker of Xbox?", a:"Microsoft"},
  {q:"Nintendos plumber?", a:"Mario"},
  {q:"Year of original PlayStation (Japan)?", a:"1994"},
  {q:"Best-selling console ever?", a:"PlayStation 2"},
  {q:"Master Chiefs game?", a:"Halo"},
  {q:"Links horse?", a:"Epona"},
  {q:"1996 N64 3D platformer?", a:"Super Mario 64"},
  {q:"Creator of Metal Gear?", a:"Hideo Kojima"},
  {q:"First console with built-in HDD as standard?", a:"Original Xbox (2001)"}
],
"Gaming": [
  {q:"What does FPS stand for?", a:"First-Person Shooter"},
  {q:"Best-selling video game ever?", a:"Minecraft"},
  {q:"Battle royale before Fortnite?", a:"PUBG"},
  {q:"Creator of Minecraft?", a:"Markus Notch Persson"},
  {q:"Engine powering Fortnite?", a:"Unreal Engine"},
  {q:"Arrow to the knee game?", a:"Skyrim"},
  {q:"The Witchers protagonist?", a:"Geralt of Rivia"},
  {q:"First successful video game (1972)?", a:"Pong"},
  {q:"Largest esports prize pool game?", a:"Dota 2 (The International)"},
  {q:"Co-founder of id Software / Doom?", a:"John Carmack"}
],
"Mohamed Salah": [
  {q:"Village hes from?", a:"Nagrig, Gharbia"},
  {q:"Current club?", a:"Liverpool FC"},
  {q:"Year he joined Liverpool?", a:"2017"},
  {q:"Italian club before Liverpool?", a:"AS Roma"},
  {q:"His nickname?", a:"The Egyptian King"},
  {q:"Number of PL Golden Boots?", a:"4"},
  {q:"First English club (2014)?", a:"Chelsea"},
  {q:"2021 AFCON final opponent?", a:"Senegal"},
  {q:"Goals in record 2017-18 PL season?", a:"32"},
  {q:"Egyptian academy that developed him?", a:"Al Mokawloon Al Arab"}
],
"Egyptian Celebrities": [
  {q:"Actor called El Zaeem?", a:"Adel Emam"},
  {q:"Star of Sahar El Layali?", a:"Mona Zaki"},
  {q:"Director of The Blue Elephant?", a:"Marwan Hamed"},
  {q:"Star of Ibrahim Labyad?", a:"Karim Abdel Aziz"},
  {q:"Actor famous for Al-Limby?", a:"Mohamed Saad"},
  {q:"Cinderella of Arab cinema?", a:"Soad Hosny"},
  {q:"Star of Kalabsh series?", a:"Amir Karara"},
  {q:"Wahsh El-Shasha actor?", a:"Farid Shawqi"},
  {q:"Director of Al-Ard (1970)?", a:"Youssef Chahine"},
  {q:"Mohamed Ramadans breakout film?", a:"Ebn Halal"}
],
"Football Player Path": [
  {q:"Sporting CP to Man United to Real Madrid to Juventus to Man United to Al-Nassr?", a:"Cristiano Ronaldo"},
  {q:"Newells to Barcelona to PSG to Inter Miami?", a:"Lionel Messi"},
  {q:"Al Mokawloon to Basel to Chelsea to Fiorentina to Roma to Liverpool?", a:"Mohamed Salah"},
  {q:"Santos to Barcelona to PSG to Al-Hilal?", a:"Neymar Jr."},
  {q:"Monaco to PSG to Real Madrid?", a:"Kylian Mbappe"},
  {q:"Everton to Man United to DC United to Everton to Derby County?", a:"Wayne Rooney"},
  {q:"Sao Paulo to AC Milan to Real Madrid to Corinthians to Sao Paulo?", a:"Kaka"},
  {q:"Schalke to Werder Bremen to Real Madrid to Arsenal to Fenerbahce?", a:"Mesut Ozil"},
  {q:"Nacional to Ajax to Liverpool to Barcelona to Atletico to Nacional to Inter Miami to Gremio?", a:"Luis Suarez"},
  {q:"Molde to Man United (as player and manager)?", a:"Ole Gunnar Solskjaer"}
],
"TikTok": [
  {q:"Parent company?", a:"ByteDance"},
  {q:"Country of ByteDance HQ?", a:"China"},
  {q:"App merged into TikTok in 2018?", a:"Musical.ly"},
  {q:"Most followed TikToker (2025)?", a:"Khaby Lame"},
  {q:"Year TikTok launched internationally?", a:"2017"},
  {q:"Max standard video length (2024)?", a:"10 minutes"},
  {q:"2020 skateboard cranberry juice Fleetwood Mac viral guy?", a:"Nathan Apodaca (Doggface)"},
  {q:"FYP stands for?", a:"For You Page"},
  {q:"First TikToker to 100M followers?", a:"Charli DAmelio"},
  {q:"ByteDances real-time recommendation system?", a:"Monolith"}
],
"Egyptian TikTok": [
  {q:"Egyptian TikToker famous for storytelling videos?", a:"Ashraf Hamdy"},
  {q:"Egyptian TikToker arrested in 2020 for family values?", a:"Haneen Hossam"},
  {q:"Other Egyptian TikToker arrested with Haneen in 2020?", a:"Mawada Al-Adham"},
  {q:"Popular Egyptian song Bent El Geran singers?", a:"Hassan Shakosh and Omar Kamal"},
  {q:"Egyptian rapper whose tracks dominate TikTok?", a:"Wegz"},
  {q:"Popular Egyptian shaabi TikTok singer?", a:"Hamo Bika"},
  {q:"Egyptian singer of Salamat trending on TikTok?", a:"Hamada Helal"},
  {q:"Wegzs viral 2022 World Cup opening song?", a:"Ezz El Arab"},
  {q:"Egyptian mahraganat artist unbanned by syndicate?", a:"Hassan Shakosh"},
  {q:"Egyptian TikToker known for cooking pranks?", a:"Menna Nasr (accept similar)"}
],
"League of Legends": [
  {q:"Developer?", a:"Riot Games"},
  {q:"Year released?", a:"2009"},
  {q:"Champions per team on Rift?", a:"5"},
  {q:"Primary map name?", a:"Summoners Rift"},
  {q:"Structure you destroy to win?", a:"Nexus"},
  {q:"Dragon granting permanent buffs after 4?", a:"Elder Dragon (via Dragon Soul)"},
  {q:"The Blind Monk champion?", a:"Lee Sin"},
  {q:"2023 Worlds winner?", a:"T1"},
  {q:"Fakers real name?", a:"Lee Sang-hyeok"},
  {q:"Home region of Jinx, Vi, Ekko?", a:"Zaun"}
],
"GTA": [
  {q:"Developer?", a:"Rockstar Games"},
  {q:"GTA stands for?", a:"Grand Theft Auto"},
  {q:"City in GTA V?", a:"Los Santos"},
  {q:"Three GTA V protagonists?", a:"Michael, Trevor, Franklin"},
  {q:"City in GTA IV?", a:"Liberty City"},
  {q:"GTA IV protagonist?", a:"Niko Bellic"},
  {q:"GTA Vs online mode?", a:"GTA Online"},
  {q:"Year of original GTA?", a:"1997"},
  {q:"80s Miami-based GTA?", a:"Vice City (2002)"},
  {q:"Female GTA VI protagonist?", a:"Lucia"}
]
};
